(define (new-syntax syntax)
  (define (tagged-list? exp tag)
    (if (pair? exp)
      (eq? (car exp) tag)
      #f))
  (define (application? exp) (tagged-list? exp 'call))
  (define (operator exp) (cadr exp))
  (define (operands exp) (cddr exp))
  (define (dispatch m)
    (cond ((eq? m 'application?) application?)
          ((eq? m 'operator) operator)
          ((eq? m 'operands) operands)
          (else (syntax m))))
  dispatch)
