(load "test.scm")
(load "4/4.2.scm")
(load "evaluator_test.scm")

(define (test)
  (define test-suite (setup-test new-application-call-syntax '() '()))
  (define (test-fn eval env)
    (assert-error (lambda () (eval '(+ 1 2) env)) "Application should start with 'call'")
    (assert-eq 3 (eval '(call + 1 2) env) "Failed eval '(call + 1 2)"))
  (test-suite test-fn))
(test)
