(load "test.scm")
(load "4/4.35.scm")
(load "evaluator_test.scm")
(load "4/4.4.scm")
(load "4/4.6.scm")

(define (test)
  (define test-suite
    (setup-test-amb (lambda (syntax) (new-derived-and-or-syntax (new-syntax syntax)))
                    '()
                    '()))
  (define (test-fn ambeval env)
    (ambeval an-integer-between env nop-succeed nop-fail)
    (assert-stream (amb->stream ambeval '(an-integer-between 3 5) env)
                   (list 3 4)
                   "Failed an-integer-between")
    (ambeval a-pythagorean-triple-between env nop-succeed nop-fail)
    (assert-stream (amb->stream ambeval '(a-pythagorean-triple-between 1 30) env)
                   (list (list 3 4 5) (list 5 12 13))
                   "Failed a-pythagorean-triple-between"))
  (test-suite test-fn))
(test)
