(load "test.scm")
(load "4/4.36.scm")
(load "evaluator_test.scm")

(define (test)
  (define (test-fn ambeval env)
    (ambeval a-pythagorean-triple env nop-succeed nop-fail)
    (assert-stream (amb->stream ambeval '(a-pythagorean-triple) env)
                   (list (list 3 4 5) (list 6 8 10) (list 5 12 13))
                   "Failed a-pythagorean-triple"))
  (full-feature-amb-suite test-fn))
(test)
