(load "test.scm")
(load "4/4.38.scm")
(load "evaluator_test.scm")
(load "stream.scm")
(load "debug.scm")

(define (test)
  (define (test-fn ambeval env)
    (with-print-time ambeval multiple-dwelling-modified env nop-succeed nop-fail)
    (assert-eq 5 (drain-amb ambeval '(multiple-dwelling-modified) env) "Failed multiple-dwelling-modified")
    ;(display-stream (amb->stream ambeval '(multiple-dwelling-modified) env) 10))
    )
  (full-feature-amb-suite test-fn))
(test)
