(load "test.scm")
(load "4/4.42.scm")
(load "evaluator_test.scm")
(load "stream.scm")
(load "debug.scm")

(define (test)
  (define (test-fn ambeval env)
    (ambeval liars env nop-succeed nop-fail)
    (assert-stream (amb->stream ambeval '(liars) env)
                   (list '((betty 3) (ethel 5) (joan 2) (kitty 1) (mary 4)))
                   "Failed liars")
    )
  (full-feature-amb-suite test-fn))
(test)
