(load "test.scm")
(load "4/4.59.scm")
(load "logic-evaluator_test.scm")

(define (test)
  (define (test-fn eval)
    (for-each eval (prepare-meeting))
    (eval (list 'assert! meeting-time))
    (assert-stream (eval '(meeting ?x (Friday ?time)))
                   '((meeting administration (Friday 1pm)))
                   "Failed meeting on Friday")
    (assert-stream (eval '(meeting-time (Hacker Alyssa P) (Wednesday ?time)))
                   '((meeting-time (Hacker Alyssa P) (Wednesday 4pm))
                     (meeting-time (Hacker Alyssa P) (Wednesday 3pm)))
                   "Failed meeting-time"))
  (setup-test test-fn))
(test)
