(load "test.scm")
(load "4/4.63.scm")
(load "logic-evaluator_test.scm")

(define (test)
  (define (test-fn eval)
    (for-each eval (prepare-database))
    (eval (list 'assert! grandson))
    (eval (list 'assert! son))
    (assert-stream (eval '(grandson Cain ?x))
                   '((grandson Cain Irad))
                   "Failed grandson")
    (assert-stream (eval '(son Lamech ?x))
                   '((son Lamech Jubal)
                     (son Lamech Jabal))
                   "Failed son")
    (assert-stream (eval '(grandson Methushael ?x))
                   '((grandson Methushael Jubal)
                     (grandson Methushael Jabal))
                   "Failed grandson"))
  (setup-test test-fn))
(test)
