(load "test.scm")
(load "3/3.26.scm")

(define (test)
  (let ((table (make-table = <)))
    (let ((insert! (table 'insert!))
          (lookup (table 'lookup)))
      (insert! 5 10)
      (insert! 8 9)
      (insert! 7 7)
      (insert! 4 2)
      (insert! 1 2)
      (insert! 1 3)
      (insert! 2 4)
      (insert! 11 3)
      (insert! 4 4)
      (assert-eq 3 (lookup 1) "Failed lookup 1")
      (assert-eq 4 (lookup 2) "Failed lookup 2")
      (assert-eq #f (lookup 3) "Failed lookup 3")
      (assert-eq 9 (lookup 8) "Failed lookup 4")
      (assert-eq #f (lookup 12) "Failed lookup 5"))))
(test)
