(define (make-joint accout old-password new-secret)
  (define (dispatch password m)
    (if (not (eq? password new-secret))
      (lambda (x) "Incorrect password")
      (accout old-password m)))
  dispatch)

(define (make-account balance secret)
  (define (withdraw amount)
    (if (> amount balance)
      "Insufficient funds"
      (begin (set! balance (- balance amount))
             balance)))
  (define (deposit amount)
    (begin (set! balance (+ balance amount))
           balance))
  (define (dispatch password m)
    (if (not (eq? password secret))
      (lambda (x) "Incorrect password")
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request: MAKE-ACCOUNT" m)))))
  dispatch)
