(load "../test.scm")
(load "2.1.scm")

(define (test)
  (let ((r1 (make-rat -2 3))
        (r2 (make-rat 2 -3))
        (r3 (make-rat -2 -3))
        (r4 (make-rat 2 3)))
    (begin (assert-eq -2 (numer r1) "Failed")
           (assert-eq 3 (denom r1) "Failed")
           (assert-eq -2 (numer r2) "Failed")
           (assert-eq 3 (denom r2) "Failed")
           (assert-eq 2 (numer r3) "Failed")
           (assert-eq 3 (denom r3) "Failed")
           (assert-eq 2 (numer r4) "Failed")
           (assert-eq 3 (denom r4) "Failed"))))
(test)
